# Generated by Django 4.2.5 on 2023-09-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="gogreenerapp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seller_name", models.CharField(max_length=100)),
                ("store_name", models.CharField(max_length=100, unique=True)),
                ("store_number", models.BigIntegerField(unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "admin_share",
                    models.CharField(
                        choices=[
                            ("", "--Select your option--"),
                            (
                                "Membership",
                                "You will be charged a monthly or yearly fee",
                            ),
                            ("Commission", "10% commission per order"),
                        ],
                        max_length=100,
                    ),
                ),
                ("password", models.CharField(max_length=100)),
                (
                    "select_city",
                    models.CharField(
                        choices=[
                            ("", "--Select an option--"),
                            ("sydney", "Sydney"),
                            ("brisbane", "Brisbane"),
                            ("melbourne", "Melbourne"),
                            ("canberra", "Canberra"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "delivery_range",
                    models.IntegerField(
                        choices=[
                            ("", "--Select an option--"),
                            (4, "Upto 4km"),
                            (5, "Upto 5km"),
                            (6, "Upto 6km"),
                            (7, "Upto 7km"),
                        ],
                        null=True,
                    ),
                ),
                ("store_address", models.CharField(max_length=100)),
                (
                    "select_id",
                    models.IntegerField(
                        choices=[
                            ("", "--Select an option--"),
                            (1, "GOGROCER101"),
                            (2, "GOGROCER102"),
                            (3, "GOGROCER103"),
                            (4, "GOGROCER104"),
                        ],
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=100, null=True, unique=True),
                ),
                ("product_price", models.IntegerField(null=True)),
                ("product_description", models.CharField(max_length=100, null=True)),
                ("product_count", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=100, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("dob", models.DateField()),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_num", models.BigIntegerField(unique=True)),
                ("password", models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
