# Generated by Django 4.2.5 on 2023-09-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gogreener", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="products",
        ),
        migrations.DeleteModel(
            name="User",
        ),
        migrations.AddField(
            model_name="gogreenerapp",
            name="language",
            field=models.CharField(
                choices=[
                    ("", "--select an option--"),
                    ("English", "English"),
                    ("Tamil", "Tamil"),
                    ("Hindi", "Hindi"),
                    ("Malayalam", "Malayalam"),
                    ("Telugu", "Telugu"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
