# Generated by Django 4.2.5 on 2023-09-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gogreener", "0002_delete_products_delete_user_gogreenerapp_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gogreenerapp",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "--select an option--"),
                    ("English", "English"),
                    ("Tamil", "Tamil"),
                    ("Hindi", "Hindi"),
                    ("Malayalam", "Malayalam"),
                    ("Telugu", "Telugu"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="gogreenerapp",
            name="store_number",
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
